import  "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";

export const metadata = {
  title: "Gaming Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AddBootstrap/>
        {children}</body>
    </html>
  );
}